version: "2"
services:
  app:
    container_name: app
    build: .
    environment:
      - MONGODB_HOST=127.0.0.1
      - MONGODB_PORT=27017
      - MONGODB_DB=facultad
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
